server:
  port: 8081

localeTag: ru-RU

telegrambot:
  botUsername: "@tourist_city_bot"
  botToken: 5484695616:AAF_w99NFVUsBzZaQQbUVLcb4WDOWif9ZX4
  botPath: https://3dfa-109-254-254-23.eu.ngrok.io

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${username}
    password: ${password}
    url: jdbc:postgresql://localhost:5432/bot
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
